name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * MON' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - name: Fixed delay to run at 1:36 AM
        run: sleep 5760 
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: enthec
          base: main
          head: main
